#!/usr/bin/env bash

grep -E '^CREATE UNIQUE INDEX' $RAW_SCHEMA > $CONSTRAINT_FILE
grep -vE '^CREATE UNIQUE INDEX' $RAW_SCHEMA > $SCHEMA_FILE


# some changes to adapt sqlite data types to pgsql
echo "BEGIN;" > "$SCHEMA_MIGRATION_FILE"
sed 's/ DATETIME/ TIMESTAMP/Ig' "$SCHEMA_FILE" >> "$SCHEMA_MIGRATION_FILE"
sed -i 's/ VARCHAR(4000)/ TEXT/Ig' "$SCHEMA_MIGRATION_FILE"
sed -i 's/CN INTEGER/CN VARCHAR(34)/Ig' "$SCHEMA_MIGRATION_FILE"
sed -i 's/"//Ig' "$SCHEMA_MIGRATION_FILE"
sed -i 's/P1PNTCNT_EU INTEGER/P1PNTCNT_EU BIGINT/Ig' "$SCHEMA_MIGRATION_FILE"
sed -i 's/P1POINTCNT INTEGER/P1POINTCNT BIGINT/Ig' "$SCHEMA_MIGRATION_FILE"
sed -i 's/P2POINTCNT INTEGER/P2POINTCNT BIGINT/Ig' "$SCHEMA_MIGRATION_FILE"
echo "COMMIT;" >> "$SCHEMA_MIGRATION_FILE"

# generate COPY statements for all tables
echo "BEGIN;" > "$CSV_MIGRATION_FILE"
while read -r table; do
    echo "\\COPY $table FROM '$CSV_DIR/$table.csv' WITH CSV HEADER;" >> $CSV_MIGRATION_FILE
done < "$TABLE_LIST"
echo "COMMIT;" >> $CSV_MIGRATION_FILE


# constraints
echo "BEGIN;" > $CONSTRAINTS_MIGRATION_FILE
cat "$CONSTRAINT_FILE" >> $CONSTRAINTS_MIGRATION_FILE

echo "COMMIT;" >> $CONSTRAINTS_MIGRATION_FILE
