#!/usr/bin/env bash



echo "SHOWING ENV VARS"
echo "DBDIR=${DBDIR}"
echo "DB=${DB}"
echo "DBUSER=${DBUSER}"
echo "PORT=${PORT}"
echo "SOCKET=${SOCKET}"
echo "SQLITE_FIADB=${SQLITE_FIADB}"
echo "TABLE_LIST=${TABLE_LIST}"
echo "CSV_DIR=${CSV_DIR}"
echo "RAW_SCHEMA=${RAW_SCHEMA}"
echo "SCHEMA_FILE=${SCHEMA_FILE}"
echo "CONSTRAINT_FILE=${CONSTRAINT_FILE}"
echo "SCHEMA_MIGRATION_FILE=${SCHEMA_MIGRATION_FILE}"
echo "CSV_MIGRATION_FILE=${CSV_MIGRATION_FILE}"
echo "CONSTRAINTS_MIGRATION_FILE=${CONSTRAINTS_MIGRATION_FILE}"
